/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zootop;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class UpdateInfo extends javax.swing.JFrame {

    /**
     * Creates new form UpdateInfo
     */
    PreparedStatement st=null;
    ResultSet rs=null;
    int q,i;
    public UpdateInfo() {
        initComponents();
    }
    public void upDateDB()
    {
        try {
            String url="jdbc:sqlserver://localhost:1433;databaseName=Zootopia";
            String username="sa";
            String password="S@dia14";
            Connection con = DriverManager.getConnection(url,username,password);
             st=con.prepareStatement("select  *from  ANIMALS");
            rs=st.executeQuery();
            ResultSetMetaData std=rs.getMetaData();
            q=std.getColumnCount();
            DefaultTableModel tblmodel=(DefaultTableModel)jTable1.getModel();
            tblmodel.setRowCount(0);
            while(rs.next())
            {
                Vector columnData=new Vector();
                for(i=1;i<=q;i++)
                {
                    columnData.add(rs.getString("animal_id"));
                    columnData.add(rs.getString("animal_name"));
                    columnData.add(rs.getString("species"));
                    columnData.add(rs.getString("gender"));
                    columnData.add(rs.getString("country_of_birth"));
                    columnData.add(rs.getString("weight"));
                            columnData.add(rs.getString("cell_no"));
                }
                tblmodel.addRow(columnData);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(UpdateInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        UpdateBtn = new javax.swing.JButton();
        Deletebtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ShowDatabtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("   Animal Id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 46, 127, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("  Animal Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 94, 127, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("   Species");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 142, 127, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("   Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 190, 127, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Country of Birth");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 238, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("     Weight");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 286, 127, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("   Cell No");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 334, 127, 30));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 46, 573, 30));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setPreferredSize(new java.awt.Dimension(84, 50));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 94, 573, 30));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 142, 573, 30));

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField4.setPreferredSize(new java.awt.Dimension(84, 50));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 190, 573, 30));

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 238, 573, 30));

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 286, 573, 30));

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 334, 573, 30));

        UpdateBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 401, 125, 47));

        Deletebtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Deletebtn.setText("Delete");
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 401, 111, 47));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Animal Id", "Animal Name", "Species", "Gender", "Country of Birth", "Weight", "Cell No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 467, 1171, 292));

        ShowDatabtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ShowDatabtn.setText("Show Data");
        ShowDatabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowDatabtnActionPerformed(evt);
            }
        });
        getContentPane().add(ShowDatabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 788, 198, 52));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 402, 153, 47));

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblmodel=(DefaultTableModel)jTable1.getModel();
        
        String tblAnimal_id=tblmodel.getValueAt(jTable1.getSelectedRow(),0).toString();
          String tblAnimalName=tblmodel.getValueAt(jTable1.getSelectedRow(),1).toString();
            String tblSpecies=tblmodel.getValueAt(jTable1.getSelectedRow(),2).toString();
              String tblGender=tblmodel.getValueAt(jTable1.getSelectedRow(),3).toString();
                String tblCountryOfBirth=tblmodel.getValueAt(jTable1.getSelectedRow(),4).toString();
                  String tblWeight=tblmodel.getValueAt(jTable1.getSelectedRow(),5).toString();
                  String tblCellNo=tblmodel.getValueAt(jTable1.getSelectedRow(),6).toString();
                  
                  jTextField1.setText(tblAnimal_id);
                   jTextField2.setText(tblAnimalName);
                    jTextField3.setText(tblSpecies);
                     jTextField4.setText(tblGender);
                      jTextField5.setText(tblCountryOfBirth);
                       jTextField6.setText(tblWeight);
                        jTextField7.setText(tblCellNo);
                        
                        
                        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void ShowDatabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowDatabtnActionPerformed
        // TODO add your handling code here:
        try {
              // jScrollPane1.setVisible(true);
             String url="jdbc:sqlserver://localhost:1433;databaseName=Zootopia";
        String username="sa";
        String password="S@dia14";
            Connection con = DriverManager.getConnection(url,username,password);
            
            Statement st=con.createStatement();
            String sql="SELECT  *FROM  ANIMALS  ";
             ResultSet rs=st.executeQuery(sql);
             
             while(rs.next())
             {
                 String animal_id=String.valueOf(rs.getInt("animal_id"));
                 String animal_name=rs.getString("animal_name");
                  String species=rs.getString("species");
                   String gender=rs.getString("gender");
                    String country_of_birth=rs.getString("country_of_birth");
                    String weight=String.valueOf(rs.getInt("weight"));
                    String cell_no=String.valueOf(rs.getInt("cell_no"));
                    
 
                     
                     String tbData[]={animal_id,animal_name,species,gender,country_of_birth,weight,cell_no};
                     DefaultTableModel tblmodel = (DefaultTableModel) jTable1.getModel();
                 tblmodel.addRow(tbData);
             }
        

            
        } catch (SQLException ex) {
            Logger.getLogger(AnimalTable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ShowDatabtnActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
         
        try {
            String url="jdbc:sqlserver://localhost:1433;databaseName=Zootopia";
        String username="sa";
        String password="S@dia14";
            Connection con = DriverManager.getConnection(url,username,password);
            String query1="UPDATE ANIMALS SET ANIMAL_NAME=?,SPECIES=?,GENDER=?,COUNTRY_OF_BIRTH=?,WEIGHT=?,CELL_NO=?  WHERE  ANIMAL_ID=?";
           PreparedStatement st=con.prepareStatement(query1);
           st.setString(1,jTextField2.getText());
             st.setString(2,jTextField3.getText());
               st.setString(3,jTextField4.getText());
                 st.setString(4,jTextField5.getText());
                   st.setString(5,jTextField6.getText());
                     st.setString(6,jTextField7.getText());
                       st.setInt(7,Integer.parseInt(jTextField1.getText()));
           st.executeUpdate();
           
                                         //upDateDB();
           
           DefaultTableModel tblmodel=(DefaultTableModel)jTable1.getModel();
         if(jTable1.getSelectedRowCount()==1)
         {
              String animal_id=jTextField1.getText();
                 String animal_name=jTextField2.getText();
                  String species=jTextField3.getText();
                   String gender=jTextField4.getText();
                    String country_of_birth=jTextField5.getText();
                    String weight=jTextField6.getText();
                    String cell_no=jTextField7.getText();
                    
                    tblmodel.setValueAt(animal_id, jTable1.getSelectedRow(), 0);
                    tblmodel.setValueAt(animal_name, jTable1.getSelectedRow(), 1);
                    tblmodel.setValueAt(species, jTable1.getSelectedRow(), 2);
                    tblmodel.setValueAt(gender, jTable1.getSelectedRow(), 3);
                    tblmodel.setValueAt(country_of_birth, jTable1.getSelectedRow(), 4);
                    tblmodel.setValueAt(weight, jTable1.getSelectedRow(), 5);
                    tblmodel.setValueAt(cell_no, jTable1.getSelectedRow(), 6);
                    //upDateDB();
                    JOptionPane.showMessageDialog(this,"Updated Successfully");
         }else{
             if(jTable1.getSelectedRowCount()==0)
             {
                  JOptionPane.showMessageDialog(this,"Table is empty");
             }
             else{
                 JOptionPane.showMessageDialog(this,"Please Select Single Row");
             }
         }
           
        } catch (SQLException ex) {
            Logger.getLogger(UpdateInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String url="jdbc:sqlserver://localhost:1433;databaseName=Zootopia";
            String username="sa";
            String password="S@dia14";
            Connection con = DriverManager.getConnection(url,username,password);
            String sql="DELETE  FROM  ANIMALS WHERE ANIMAL_ID=? ";
            PreparedStatement st=con.prepareStatement(sql);
            
            st.setInt(1,Integer.parseInt(jTextField1.getText()));
          
                  st.executeUpdate();
                  
                  con.close();
                  
                      JOptionPane.showMessageDialog(this,"Record is Deleted");  
                       DefaultTableModel tblmodel=(DefaultTableModel)jTable1.getModel();
         if(jTable1.getSelectedRowCount()==1)
         {
             tblmodel.removeRow(jTable1.getSelectedRow());
              
                    JOptionPane.showMessageDialog(this,"Deleted Successfully");
         }else{
             if(jTable1.getSelectedRowCount()==0)
             {
                  JOptionPane.showMessageDialog(this,"Table is empty");
             }
             else{
                 JOptionPane.showMessageDialog(this,"Please Select Single Row");
             }
         }
           
                      
                      
            
            
        } catch (SQLException ex) {
            Logger.getLogger(UpdateEnclosure.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeletebtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          new Options_Frame().setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deletebtn;
    private javax.swing.JButton ShowDatabtn;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
