/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zootop;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class UpdateEnclosure extends javax.swing.JFrame {

    /**
     * Creates new form UpdateEnclosure
     */
    public UpdateEnclosure() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        UpdateBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("   Cell No");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 83, 131, 35));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("  Employee Id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 136, 131, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText(" Total Animal");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 175, 131, 35));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("   Cell type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 228, 131, 35));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("    Location");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 281, 131, 35));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 83, 530, 35));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 136, 530, 35));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 175, 530, 35));

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 228, 530, 35));

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 281, 530, 35));

        UpdateBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 373, 130, 39));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 378, 136, 39));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cell_No", "Employee_Id", "Total_Animal", "Cell_Type", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 455, 1173, 327));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton3.setText("Show Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 844, 134, 47));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 374, 129, 48));

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 950));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         DefaultTableModel tblmodel=(DefaultTableModel)jTable1.getModel();
        
        String tblCell_No=tblmodel.getValueAt(jTable1.getSelectedRow(),0).toString();
          String tblEmployee_Id=tblmodel.getValueAt(jTable1.getSelectedRow(),1).toString();
            String tblTotal_Animal=tblmodel.getValueAt(jTable1.getSelectedRow(),2).toString();
              String tblCell_Type=tblmodel.getValueAt(jTable1.getSelectedRow(),3).toString();
                String tblLocation=tblmodel.getValueAt(jTable1.getSelectedRow(),4).toString();
                 
                  
                  jTextField1.setText(tblCell_No);
                   jTextField2.setText(tblEmployee_Id);
                    jTextField3.setText(tblTotal_Animal);
                     jTextField4.setText(tblCell_Type);
                      jTextField5.setText(tblLocation);
                     
                        
                        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
        try {
            String url="jdbc:sqlserver://localhost:1433;databaseName=Zootopia";
        String username="sa";
        String password="S@dia14";
            Connection con = DriverManager.getConnection(url,username,password);
            String query1="UPDATE ENCLOSURE SET EMPLOYEE_ID=?,TOTAL_ANIMAL=?,CELL_TYPE=?,LOCATION=?  WHERE  CELL_NO=?";
           PreparedStatement st=con.prepareStatement(query1);
           st.setInt(1,Integer.parseInt(jTextField2.getText()));
           st.setInt(2,Integer.parseInt(jTextField3.getText()));
               st.setString(3,jTextField4.getText());
                 st.setString(4,jTextField5.getText());
                  
                       st.setInt(5,Integer.parseInt(jTextField1.getText()));
           st.executeUpdate();
           
                                         //upDateDB();
           
           DefaultTableModel tblmodel=(DefaultTableModel)jTable1.getModel();
         if(jTable1.getSelectedRowCount()==1)
         {
              String cell_no=jTextField1.getText();
                 String employee_id=jTextField2.getText();
                  String total_animal=jTextField3.getText();
                   String cell_type=jTextField4.getText();
                    String location=jTextField5.getText();
                    
                    
                    tblmodel.setValueAt(cell_no, jTable1.getSelectedRow(), 0);
                    tblmodel.setValueAt(employee_id, jTable1.getSelectedRow(), 1);
                    tblmodel.setValueAt(total_animal, jTable1.getSelectedRow(), 2);
                    tblmodel.setValueAt(cell_type, jTable1.getSelectedRow(), 3);
                    tblmodel.setValueAt(location, jTable1.getSelectedRow(), 4);
                    
                   // upDateDB();
                    JOptionPane.showMessageDialog(this,"Updated Successfully");
         }else{
             if(jTable1.getSelectedRowCount()==0)
             {
                  JOptionPane.showMessageDialog(this,"Table is empty");
             }
             else{
                 JOptionPane.showMessageDialog(this,"Please Select Single Row");
             }
         }
           
        } catch (SQLException ex) {
            Logger.getLogger(UpdateInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
         try {
              // jScrollPane1.setVisible(true);
             String url="jdbc:sqlserver://localhost:1433;databaseName=Zootopia";
        String username="sa";
        String password="S@dia14";
            Connection con = DriverManager.getConnection(url,username,password);
            
            Statement st=con.createStatement();
            String sql="SELECT  *FROM  ENCLOSURE  ";
             ResultSet rs=st.executeQuery(sql);
             
             while(rs.next())
             {
                 String cell_no=String.valueOf(rs.getInt("cell_no"));
                 String employee_id=rs.getString("employee_id");
                  String total_animal=rs.getString("total_animal");
                   String cell_type=rs.getString("cell_type");
                    String location=rs.getString("location");
                 
                    
 
                     
                     String tbData[]={cell_no,employee_id,total_animal,cell_type,location};
                     DefaultTableModel tblmodel = (DefaultTableModel) jTable1.getModel();
                 tblmodel.addRow(tbData);
             }
        

            
        } catch (SQLException ex) {
            Logger.getLogger(AnimalTable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            String url="jdbc:sqlserver://localhost:1433;databaseName=Zootopia";
            String username="sa";
            String password="S@dia14";
            Connection con = DriverManager.getConnection(url,username,password);
            String sql="DELETE  FROM  ENCLOSURE WHERE CELL_NO=? ";
            PreparedStatement st=con.prepareStatement(sql);
            
            st.setInt(1,Integer.parseInt(jTextField1.getText()));
          
                  st.executeUpdate();
                  
                  con.close();
                  
                      JOptionPane.showMessageDialog(this,"Record is Deleted");  
                       DefaultTableModel tblmodel=(DefaultTableModel)jTable1.getModel();
         if(jTable1.getSelectedRowCount()==1)
         {
             tblmodel.removeRow(jTable1.getSelectedRow());
              
                    JOptionPane.showMessageDialog(this,"Deleted Successfully");
         }else{
             if(jTable1.getSelectedRowCount()==0)
             {
                  JOptionPane.showMessageDialog(this,"Table is empty");
             }
             else{
                 JOptionPane.showMessageDialog(this,"Please Select Single Row");
             }
         }
           
                      
                      
            
            
        } catch (SQLException ex) {
            Logger.getLogger(UpdateEnclosure.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new Options_Frame().setVisible(true);
        this.setVisible(false);      // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateEnclosure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateEnclosure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateEnclosure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateEnclosure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateEnclosure().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
